# -*- coding: utf-8 -*-
"""automation_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UuXjmRsJWmCHGP8lzGbRI2NF_dNRZQno
"""

import json
import os
import subprocess

# Define the missing project_dir variable
project_dir = '/content'

# Populate network_check_code with the script contents
network_check_code = """import json
import os

def load_inventory(filepath):
    with open(filepath, 'r') as f:
        return json.load(f)

def simulate_ping(ip):
    return ip is not None

def run_checks():
    inventory_path = '/content/inventory.json'
    output_path = '/content/output.json'

    if not os.path.exists(inventory_path):
        print(f"Error: {inventory_path} not found.")
        return

    inventory = load_inventory(inventory_path)
    results = {}

    # Dynamically handle both list and dictionary formats for the inventory file
    devices = inventory if isinstance(inventory, list) else inventory.get('devices', [])

    print("Starting network check for Cisco devices...")
    for device in devices:
        if not isinstance(device, dict):
            continue
        hostname = device.get('hostname', 'unknown_host')
        ip = device.get('ip', None)
        configured_status = device.get('status', 'inactive')

        print(f"Checking {hostname} ({ip})...")

        ping_success = simulate_ping(ip) if configured_status == 'active' else False

        results[hostname] = {
            "ip": ip,
            "reachable": ping_success,
            "status": "Online" if ping_success else "Offline",
            "device_type": device.get('type', 'unknown')
        }

    with open(output_path, 'w') as f:
        json.dump(results, f, indent=4)

    print(f"Automation check complete. Results saved to {output_path}.")

if __name__ == '__main__':
    run_checks()
"""

def load_inventory(filepath):
    with open(filepath, 'r') as f:
        return json.load(f)

def simulate_ping(ip):
    return ip is not None

def run_checks():
    inventory_path = '/content/inventory.json'
    output_path = '/content/output.json'

    if not os.path.exists(inventory_path):
        print(f"Error: {inventory_path} not found.")
        return

    inventory = load_inventory(inventory_path)
    results = {}

    # Dynamically handle both list and dictionary formats for the inventory file
    devices = inventory if isinstance(inventory, list) else inventory.get('devices', [])

    print("Starting network check for Cisco devices...")
    for device in devices:
        if not isinstance(device, dict):
            continue
        hostname = device.get('hostname', 'unknown_host')
        ip = device.get('ip', None)
        configured_status = device.get('status', 'inactive')

        print(f"Checking {hostname} ({ip})...")

        # Simulation logic
        ping_success = simulate_ping(ip) if configured_status == 'active' else False

        results[hostname] = {
            "ip": ip,
            "reachable": ping_success,
            "status": "Online" if ping_success else "Offline",
            "device_type": device.get('type', 'unknown')
        }

    with open(output_path, 'w') as f:
        json.dump(results, f, indent=4)

    print(f"Automation check complete. Results saved to {output_path}.")

if __name__ == '__main__':
    run_checks()

# Safely write the file to the project directory
with open(os.path.join(project_dir, 'network_check.py'), 'w') as f:
    f.write(network_check_code)

print("network_check.py written successfully.")

import os
import json
import subprocess

project_dir = '/content/automation_project'
os.makedirs(project_dir, exist_ok=True)

# 1. Save the correct inventory to automation_project/inventory.json
inventory_data = [
    {
        "hostname": "R1-West",
        "Management IP address": "10.35.1.1",
        "device type": "Cisco 2911",
        "location": "Makati Branch Office",
        "status": "Active"
    },
    {
        "hostname":  "R2-South",
        "Management IP address": "10.35.2.1",
        "device type": "Cisco ISR 4331",
        "location": "Bicutan Main",
        "status": "Maintenance"
    },
    {
        "hostname":  "R3-North",
        "Management IP address": "10.35.3.4",
        "device type": "Cisco 2811",
        "location": "Clark Branch Office",
        "status": "Maintenance"
    }
]

with open(os.path.join(project_dir, 'inventory.json'), 'w') as f:
    json.dump(inventory_data, f, indent=4)

# 2. Save the network_check.py using matching keys
network_check_code = """import json
import os

def load_inventory(filepath):
    with open(filepath, 'r') as f:
        return json.load(f)

def simulate_ping(ip):
    return ip is not None

def run_checks():
    current_dir = os.path.dirname(os.path.abspath(__file__))
    inventory_path = os.path.join(current_dir, 'inventory.json')
    output_path = os.path.join(current_dir, 'output.json')

    if not os.path.exists(inventory_path):
        print(f"Error: {inventory_path} not found.")
        return

    inventory = load_inventory(inventory_path)
    results = {}

    devices = inventory if isinstance(inventory, list) else inventory.get('devices', [])

    print("Starting network check for Cisco devices...")
    for device in devices:
        if not isinstance(device, dict):
            continue
        hostname = device.get('hostname', 'unknown_host')
        ip = device.get('Management IP address', None)
        configured_status = device.get('status', 'Inactive')

        print(f"Checking {hostname} ({ip})...")

        # Status is 'Active' in user inventory schema
        ping_success = simulate_ping(ip) if configured_status == 'Active' else False

        results[hostname] = {
            "ip": ip,
            "reachable": ping_success,
            "status": "Online" if ping_success else "Offline",
            "device_type": device.get('device type', 'unknown')
        }

    with open(output_path, 'w') as f:
        json.dump(results, f, indent=4)

    print(f"Automation check complete. Results saved to {output_path}.")

if __name__ == '__main__':
    run_checks()
"""

with open(os.path.join(project_dir, 'network_check.py'), 'w') as f:
    f.write(network_check_code)

# 3. Save README.md
readme_content = """# Mini Network Automation Project

This project simulates a baseline network connectivity check against managed Cisco hardware.

## Structure
- `inventory.json`: Managed network nodes.
- `network_check.py`: Execution automation script.
- `output.json`: Status summary output.
- `README.md`: Basic usage documentation.

## How to Run
Execute `python network_check.py` inside the `automation_project/` folder.
"""

with open(os.path.join(project_dir, 'README.md'), 'w') as f:
    f.write(readme_content)

# Run the newly created network check script to generate automation_project/output.json
print("Executing project-specific checks...")
subprocess.run(["python", os.path.join(project_dir, 'network_check.py')], check=True)