# -*- coding: utf-8 -*-
"""interface_automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JkiE3rNqMpoXwaB41_UMEuMXNehqVxOE
"""

import requests
import json
import urllib3
from requests.auth import HTTPBasicAuth

# Disable SSL certificate warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# CREDENTIALS FOR DEVNET

HOSTNAME = "devnetsandboxiosxec8k.cisco.com"
USERNAME = "jasperconcepcion28"
PASSWORD = "uIC_5dg_Dr36"

# RESTCONF base URL
BASE_URL = f"https://{HOSTNAME}/restconf/data"

# Authentication
AUTH = HTTPBasicAuth(USERNAME, PASSWORD)

# RESTCONF headers
HEADERS = {
    "Accept": "application/yang-data+json",
    "Content-Type": "application/yang-data+json"
}


# 1. JSON Configuration Payload

payload = {
    "ietf-interfaces:interface": {
        "name": "Loopback100",
        "description": "Configured using RESTCONF",
        "type": "iana-if-type:softwareLoopback",
        "enabled": True,
        "ietf-ip:ipv4": {
            "address": [
                {
                    "ip": "192.0.2.100",
                    "netmask": "255.255.255.0"
                }
            ]
        }
    }
}


# 2. RESTCONF URL

interfaces_url = (
    f"{BASE_URL}/ietf-interfaces:interfaces"
)

loopback_url = (
    f"{BASE_URL}/ietf-interfaces:interfaces/"
    f"interface=Loopback100"
)


# 3. Configure Loopback100

print("=" * 60)
print("RESTCONF - Loopback100 Configuration (PUT)")
print("=" * 60)

try:
    response = requests.put(
        loopback_url,
        headers=HEADERS,
        auth=AUTH,
        json=payload,
        verify=False
    )

    print(f"Configuration HTTP Status: {response.status_code}")

    if response.status_code in [200, 201, 204]:
        print("SUCCESS: Loopback100 configuration succeeded.")

    else:
        print("FAILED: Loopback100 configuration failed.")
        print("Router response:")
        print(response.text)

except requests.exceptions.RequestException as error:
    print("ERROR: Unable to connect to the RESTCONF server.")
    print(error)

# 4. Retrieve Loopback100

print("\n" + "=" * 60)
print("Verifying Loopback100")
print("=" * 60)

try:
    verify_response = requests.get(
        loopback_url,
        headers={
            "Accept": "application/yang-data+json"
        },
        auth=AUTH,
        verify=False
    )

    print(f"Verification HTTP Status: {verify_response.status_code}")

    if verify_response.status_code == 200:

        print("SUCCESS: Loopback100 was retrieved.")
        print("\nLoopback100 Configuration:")

        configuration = verify_response.json()

        print(json.dumps(configuration, indent=4))

    else:
        print("FAILED: Could not retrieve Loopback100.")
        print(verify_response.text)

except requests.exceptions.RequestException as error:
    print("ERROR: Unable to retrieve Loopback100.")
    print(error)

