# -*- coding: utf-8 -*-
"""network_inventory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZrHOInt8cpnE7b0Vd15JU3HcyCqvCTA
"""

network_inv = [
    {
        "hostname": "R1-West",
        "Management IP address": "10.35.1.1",
        "device type": "Cisco 2911",
        "location": "Makati Branch Office",
        "status": "Active"
    },
    {
        "hostname":  "R2-South",
        "Management IP address": "10.35.2.1",
        "device type": "Cisco ISR 4331",
        "location": "Bicutan Main",
        "status": "Maintenance",
    },

    {
        "hostname":  "R3-North",
        "Management IP address": "10.35.3.4",
        "device type": "Cisco 2811",
        "location": "Clark Branch Office",
        "status": "Maintenance",
    }
]

# 2 Display All Devices

print("=== ALL DEVICES IN INVENTORY ===")

for device in network_inv:
  print(f"Hostname: {device['hostname']}"),
  print(f"Management IP address: {device['Management IP address']}"),
  print(f"Device Type: {device['device type']}"),
  print(f"Location: {device['location']}"),
  print(f"Status: {device['status']}"),
  print("=" * 45)

print("\n")
# 2 Active Devices

print("=== ALL ACTIVE DEVICES ===")
for device in network_inv:
  if device["status"] == "Active":
    print(f"Hostname: {device['hostname']}"),
    print(f"Management IP address: {device['Management IP address']}"),
    print(f"Device Type: {device['device type']}"),
    print(f"Location: {device['location']}"),
    print(f"Status: {device['status']}"),
    print("=" * 45)

print("\n")
# 3 Number of operational devices

print("=== NUMBER OF OPERATIONAL DEVICES ===")
active_ct= 0
for device in network_inv:
  if device["status"] == "Active":
    active_ct += 1
print(f"Total operational (Active) devices: {active_ct}")