# -*- coding: utf-8 -*-
"""restconf_monitor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0wStW8YGOQOon6wdsl1Fs9KeOSoFplV
"""

import requests
import urllib3

# Disable SSL warnings for the sandbox self-signed certificate
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Sandbox Details
HOST = 'devnetsandboxiosxec8k.cisco.com'
PORT = '443'
USER = 'jasperconcepcion28'
PASS = 'uIC_5dg_Dr36'

# RESTCONFAPI Details
url = f"https://{HOST}:{PORT}/restconf/data/ietf-interfaces:interfaces"
headers = {
    "Accept": "application/yang-data+json",
    "Content-Type": "application/yang-data+json"
}

try:
    response = requests.get(
        url,
        auth=(USER, PASS),
        headers=headers,
        verify=False,
        timeout=10
    )
    print(f"HTTP Status Code: {response.status_code}\n")

    if response.status_code == 200:
        data = response.json()
        interfaces = data.get("ietf-interfaces:interfaces", {}).get("interface", [])

        print("=== Interface Status ===")
        for interface in interfaces:
            name = interface.get("name", "Unknown")
            enabled = interface.get("enabled", False)
            print(f"Interface: {name:<20} | Enabled: {enabled}")
    else:
        print("Failed to retrieve data. Response details:\n{response.text}")

except requests.exceptions.RequestException as e:
    print("An error occurred while connecting to the router: {e}")

